### ISSUE TITLE
Get boundary nodes for tag boundary

### ISSUE THREAD

**Issue by InfoDevkota** [pelias/pbf2json#105]
we can get the way nodes using `--waynodes=true`.

Is it possible to get boundary nodes as well? I am looking to get boundary of tag `"boundary":"administrative"`

I am not sure if this request fits the original purpose of this tool, to be useful for geocoding. If this does and is possible to develop, I would like to involve in developing this feature.

**Comment by missinglink** [comment]
Hi @InfoDevkota 

This library doesn't assemble polygons, I recommend https://docs.osmcode.org/osmium/latest/osmium-export.html for that task.

An example `boundaries_config.json` file:

```json
{
  "attributes": {
    "type": true,
    "id": true
  },
  "linear_tags": [
    "boundary=!multipolygon,administrative,postal_code",
    "landuse=!residential",
    "type=!boundary"
  ],
  "area_tags": [
    "boundary=multipolygon,administrative,postal_code",
    "landuse=residential",
    "type=boundary"
  ]
}
```

```bash
# generate osmium boundaries GeoJSON json lines file
osmium export \
  'filename.pbf' \
   --omit-rs --show-errors --progress \
   -F pbf -f geojsonseq \
   -i sparse_file_array \
   -c 'boundaries_config.json'
```

You may optionally want to do some post-processing on the file:

```bash
grep '"type":"\(Multi\)\?\(Point\|Polygon\)"' |\
    grep -e '"name":' -e '"boundary":"postal_code"' |\
    grep -e '"boundary"' -e '"landuse"' -e '"place"'
```

**Comment by missinglink** [comment]
Here's an example of a boundary extracted with this method:
https://spatial.demo.geocode.earth/explore/place/osm/relation:4583247

**Comment by missinglink** [comment]
Also worth mentioning https://osm-boundaries.com/Map

**Comment by InfoDevkota** [comment]
Thank you!

You Pick Kathmandu on the example. 🤗
