### ISSUE TITLE
some data was lost after parse pbf to json.

### ISSUE THREAD

**Issue by wenyiduo888** [pelias/pbf2json#112]
Hi,i found that some data was lost after parse pbf to json.
dataset:https://download.geofabrik.de/north-america/us-midwest-latest.osm.pbf
us-midwest include Illinois.
i run the code below:
./pbf2json.linux-x64 -tags='cemetery' us-midwest-latest.osm.pbf > cemetery.log

i can search Sunset Hill Cemetery in Illinois on openstreetmap.com

but i can not get Sunset Hill Cemetery in cemetery.log

What's the problem?

**Comment by missinglink** [comment]
Please provide a link to the OSM record

**Comment by missinglink** [comment]
Maybe it's [this one](https://www.openstreetmap.org/way/773077884)?

If so, then you have provided the wrong tags, the tag is `landuse~ cemetery`

<img width="338" alt="Screenshot 2023-01-11 at 16 37 03" src="https://user-images.githubusercontent.com/738069/211848719-f7153b46-dbdd-4602-9b62-fd07885ccb56.png">

**Comment by wenyiduo888** [comment]
Fast Response.
and i use landuse~cemetery tags get the right result.
i was wrong.
thanks.

**Comment by wenyiduo888** [comment]
hi, @missinglink   
I still have some questions about this issue.
i run
./pbf2json.linux-x64 -tags='cemetery' us-midwest-latest.osm.pbf > cemetery1.log
./pbf2json.linux-x64 -tags='landuse~cemetery' us-midwest-latest.osm.pbf > cemetery2.log
The contents of files cemetery1.log and cemetery2.log are not the same.

I want to know if I can get all the content of cemetery by run below?
./pbf2json.linux-x64 -tags='cemetery,landuse~cemetery' us-midwest-latest.osm.pbf > cemetery_all.log

thanks.
