### ISSUE TITLE
leveldb:PUT performace

### ISSUE THREAD

**Issue by missinglink** [pelias/pbf2json#2]
We may be able to get better performance on PUT operations to `leveldb` by batching the PUT operations and/or using an `async` approach rather than a `sync` one to avoid blocking while waiting for the `I/O` operation to resolve.

Requires some investigation.

ref: https://github.com/google/leveldb#features

```
The basic operations are Put(key,value), Get(key), Delete(key).
Multiple changes can be made in one atomic batch.
```

**Comment by sevko** [comment]
As per the [goleveldb documentation]():

```
batch := new(leveldb.Batch)
batch.Put([]byte("foo"), []byte("value"))
batch.Put([]byte("bar"), []byte("another value"))
batch.Delete([]byte("baz"))
err = db.Write(batch, nil)
```

Would be nice to ship this for our next OSM import.
