### ISSUE TITLE
Extract All Tags!

### ISSUE THREAD

**Issue by rahimramezanian** [pelias/pbf2json#48]
Hi.
Is it possible to extract all tags from a pbf file?
in a command like this

`$ ./build/pbf2json.linux-x64 -tags="ALLTAGS" /tmp/wellington_new-zealand.osm.pbf`
Thanks.

**Comment by missinglink** [comment]
this is not currently supported. the openstreetmap contains a lot of data. this tool was originally created in order to extract the entities useful for geocoding, so we remove things like trees, dolphins and street lights (yes those are all things).

Could you explain your use case?

**Comment by rahimramezanian** [comment]
OK in this case using a list of tags similar to your config is more useful. Thanks for your response.
